### ISSUE TITLE
why it doesn't work?

### ISSUE THREAD

**Issue by davidxiao** [davidxiao/tvtest#1]
hi, @ntf
   sorry for direct message, mate, 
   i just got some time to play with tv, wondering if can you pls help why my test doesn't work? it doesn't show any error, but doesn't show TV at all

Thanks
David Xiao

**Comment by ntf** [comment]
Please atttach a sample with a link, it is unlikely that people would clone your project from git and run locally.

**Comment by davidxiao** [comment]
thanks, mate
